// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pgwwfultxuzeokcajdry.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBnd3dmdWx0eHV6ZW9rY2FqZHJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMDA4MjgsImV4cCI6MjA2MjY3NjgyOH0.XM3HxVzTx-tFl0M-Q2VBBQLxyg6WV85kfyazUium7O4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);